import { useMemo, useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { Button, NumberField, Section, TextField, SelectRow } from '../components/ui.jsx'
import Icon from '../components/Icon.jsx'
import { todayISO } from '../lib/format.js'
import { addNutrients, createFood, createMeal, diaryGroups, nutrientsForAmount, nutritionTotalForDate, nutritionTotalForMeals } from '../lib/nutrition.js'
import { lookupFoodBarcode, normalizeBarcode } from '../lib/food-api.js'
import { MOBILE } from '../lib/mobile.js'
import { scanCode } from '../lib/scan.js'
import CameraScan from '../components/CameraScan.jsx'

const TYPES = [{ value: 'breakfast', label: 'Breakfast' }, { value: 'lunch', label: 'Lunch' }, { value: 'dinner', label: 'Dinner' }, { value: 'snack', label: 'Snacks' }]
const FIELDS = [['calories', 'Calories', 'kcal'], ['protein', 'Protein', 'g'], ['carbs', 'Carbs', 'g'], ['fat', 'Fat', 'g'], ['fiber', 'Fiber', 'g']]
const emptyForm = () => ({ name: '', brand: '', barcode: '', servingSize: 1, servingUnit: 'serving', calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 })
const labelOf = type => TYPES.find(item => item.value === type)?.label || type
function Stat({ label, value, target, unit = 'g' }) { return <div><div className="small dim">{label}</div><div className="big" style={{ fontSize: 21 }}>{Math.round(value)}<span className="muted" style={{ fontSize: 11 }}> {unit}{target ? ` / ${Math.round(target)}` : ''}</span></div></div> }
function MacroLine({ label, value, target, color = 'var(--acc)', unit = 'g' }) { const pct = target ? Math.min(100, Math.round(value / target * 100)) : 0; return <div style={{ marginTop: 10 }}><div className="row between small"><span>{label}</span><span className="muted">{Math.round(value)}{target ? ` / ${Math.round(target)}` : ''} {unit}</span></div>{target && <div style={{ height: 6, background: 'var(--surface-3)', borderRadius: 8, marginTop: 5 }}><div style={{ width: `${pct}%`, height: '100%', borderRadius: 8, background: color }} /></div>}</div> }

export default function Nutrition() {
  const nav = useNavigate(); const location = useLocation(); const S = useStore(s => s.S); const update = useStore(s => s.update)
  const [tab, setTab] = useState(() => location.state?.tab === 'add' ? 'add' : 'diary'); const [query, setQuery] = useState(''); const [barcode, setBarcode] = useState(''); const [scanOpen, setScanOpen] = useState(false); const [status, setStatus] = useState('')
  const [foodId, setFoodId] = useState(null); const [servings, setServings] = useState(1); const [mealType, setMealType] = useState('snack'); const [form, setForm] = useState(emptyForm()); const [showForm, setShowForm] = useState(false)
  const date = todayISO(); const foods = S.foods || []; const meals = S.meals || []; const targets = S.nutritionTargets || {}; const total = useMemo(() => nutritionTotalForDate(meals, date), [meals, date]); const groups = useMemo(() => diaryGroups(meals, date), [meals, date]); const selected = foods.find(f => f.id === foodId)
  const recent = [...meals].reverse().map(m => foods.find(f => f.id === m.foodId)).filter(Boolean).filter((food, i, all) => all.findIndex(f => f.id === food.id) === i).slice(0, 6)
  const visible = foods.filter(f => `${f.name} ${f.brand}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8)
  const set = (k, v) => setForm(x => ({ ...x, [k]: v }))
  const saveFood = data => { if (!data.name?.trim()) return; const food = createFood(data); update(s => { s.foods = [...(s.foods || []).filter(f => !food.barcode || f.barcode !== food.barcode), food] }); setFoodId(food.id); setShowForm(false); setForm(emptyForm()); setStatus('Food saved. Check the label values before logging.') }
  const lookup = async code => { setStatus('Looking up product…'); try { const data = await lookupFoodBarcode(code); saveFood(data); setBarcode(''); setStatus(`Found ${data.name}.`) } catch (e) { setStatus(e.message); setShowForm(true); set('barcode', normalizeBarcode(code)) } }
  const found = code => { setScanOpen(false); lookup(code.value) }
  const logMeal = (food = selected, type = mealType, amount = servings) => { if (!food) return; const snapshot = nutrientsForAmount(food.nutrientsPerServing, amount); update(s => { s.meals = [...(s.meals || []), createMeal({ date, mealType: type, foodId: food.id, foodName: food.name, servings: amount, nutrients: snapshot })] }); setFoodId(null); setServings(1); setStatus(`${food.name} added to ${labelOf(type).toLowerCase()}.`) }
  const saveTargets = e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget).entries()); update(s => { s.nutritionTargets = Object.fromEntries(['calories', 'protein', 'carbs', 'fat'].map(k => [k, Number(data[k]) || null])) }); setStatus('Daily goals saved.') }
  const makePlan = () => { const pool = foods.slice().sort((a, b) => (b.nutrientsPerServing.protein || 0) - (a.nutrientsPerServing.protein || 0)); const picks = [pool[0], pool[1], pool[2], pool[3]].filter(Boolean); if (!picks.length) { setStatus('Save foods first, then I can build a plan.'); return } update(s => { s.mealPlans = [...(s.mealPlans || []).filter(p => p.date !== date), { date, createdAt: new Date().toISOString(), meals: picks.map((f, i) => ({ mealType: TYPES[i].value, foodId: f.id, foodName: f.name, servings: 1 })) }] }); setStatus('Today’s plan is ready.') }
  const plan = (S.mealPlans || []).find(p => p.date === date); const plannedTotal = nutritionTotalForMeals(plan?.meals || [], foods)
  return <div className="narrow">
    <div className="hdr"><div><h1>Nutrition</h1><div className="sub">Food diary · {date}</div></div><button className="iconbtn" onClick={() => nav('/home')} aria-label="Back"><Icon name="chevronLeft" /></button></div>
    <div className="card"><div className="row" style={{ justifyContent: 'space-between', gap: 7 }}><Stat label="Calories" value={total.calories} target={targets.calories} unit="kcal" /><Stat label="Protein" value={total.protein} target={targets.protein} /><Stat label="Carbs" value={total.carbs} target={targets.carbs} /><Stat label="Fat" value={total.fat} target={targets.fat} /></div><MacroLine label="Calories" value={total.calories} target={targets.calories} unit="kcal" color="var(--orange)" /><MacroLine label="Protein" value={total.protein} target={targets.protein} color="var(--acc)" /></div>
    <div className="segmented" style={{ marginBottom: 18 }}><button className={tab === 'diary' ? 'on' : ''} onClick={() => setTab('diary')}>Diary</button><button className={tab === 'add' ? 'on' : ''} onClick={() => setTab('add')}>Add food</button><button className={tab === 'plan' ? 'on' : ''} onClick={() => setTab('plan')}>Plan</button><button className={tab === 'targets' ? 'on' : ''} onClick={() => setTab('targets')}>Goals</button></div>
    {status && <div className="notice" role="status">{status}</div>}
    {tab === 'diary' && <><Section title="Food diary"><div className="small muted" style={{ marginBottom: 8 }}>Tap a recent food to add it again.</div>{recent.length > 0 && <div className="row" style={{ flexWrap: 'wrap', gap: 6, marginBottom: 12 }}>{recent.map(food => <Button key={food.id} size="sm" onClick={() => logMeal(food)}>{food.name}</Button>)}</div>}{groups.map(group => <div key={group.type} className="card" style={{ margin: '8px 0', padding: 12 }}><div className="row between" style={{ marginBottom: 4 }}><h3 style={{ margin: 0 }}>{labelOf(group.type)}</h3><span className="small muted">{Math.round(group.total.calories)} kcal · {Math.round(group.total.protein)}g protein</span></div>{group.meals.map(meal => <div className="lrow" key={meal.id}><span className="lrow-m"><span className="lrow-t">{meal.foodName}</span><span className="lrow-s">{meal.servings} serving{meal.servings === 1 ? '' : 's'} · {Math.round(meal.nutrientsSnapshot.calories)} kcal</span></span><span className="lrow-v">{Math.round(meal.nutrientsSnapshot.protein)}g</span></div>)}<Button size="sm" onClick={() => { setMealType(group.type); setTab('add') }}>+ Add to {labelOf(group.type)}</Button></div>)}{!groups.length && <div className="empty"><div className="muted small">Your diary is empty. Add breakfast, lunch, dinner, or a snack.</div></div>}</Section><Section title="Workout connection"><div className="lrow"><span className="lrow-m"><span className="lrow-t">{S.active ? 'Workout in progress' : (S.workouts || []).some(w => w.d === date) ? 'Workout completed today' : 'No workout logged today'}</span><span className="lrow-s">Nutrition and training stay in the same daily record.</span></span><Button size="sm" onClick={() => nav(S.active ? '/workout' : '/plan')}>{S.active ? 'Resume' : 'Plan'}</Button></div></Section></>}
    {tab === 'add' && <><Section title="Find food"><div className="row" style={{ gap: 8 }}><TextField value={query} onChange={e => setQuery(e.target.value)} placeholder="Search foods" aria-label="Search foods" />{query && <Button size="sm" onClick={() => setShowForm(true)}>Manual</Button>}</div>{query && visible.map(food => <button className="lrow tap" key={food.id} onClick={() => { setFoodId(food.id); setQuery('') }}><span className="lrow-m"><span className="lrow-t">{food.name}</span><span className="lrow-s">{food.brand || 'Saved'} · {food.nutrientsPerServing.calories} kcal / serving</span></span></button>)}</Section><Section title="Scan or create"><div className="row" style={{ gap: 8 }}><TextField value={barcode} onChange={e => setBarcode(e.target.value)} placeholder="UPC / EAN barcode" aria-label="Barcode" inputMode="numeric" /><Button size="sm" onClick={() => lookup(barcode)} disabled={!barcode}>Look up</Button></div><div className="row" style={{ gap: 8, marginTop: 8 }}><Button size="sm" icon="camera" onClick={async () => { if (MOBILE) { try { const c = await scanCode(); if (c) lookup(c.value) } catch (e) { setStatus(e.message || 'Scanner unavailable.') } } else setScanOpen(true) }}>Scan barcode</Button><Button size="sm" icon="plus" onClick={() => setShowForm(v => !v)}>Manual food</Button></div>{scanOpen && <div className="card" style={{ marginTop: 12 }}><CameraScan onFound={found} onCancel={() => setScanOpen(false)} /></div>}</Section>{showForm && <div className="card"><h2>Food label</h2><TextField value={form.name} onChange={e => set('name', e.target.value)} placeholder="Food name" aria-label="Food name" /><TextField value={form.brand} onChange={e => set('brand', e.target.value)} placeholder="Brand (optional)" aria-label="Brand" /><div className="row" style={{ flexWrap: 'wrap', gap: 8, marginTop: 8 }}>{FIELDS.map(([k, label, unit]) => <label key={k} style={{ flex: '1 1 90px' }}><span className="small dim">{label} ({unit})</span><NumberField value={form[k]} onChange={v => set(k, v)} aria-label={label} /></label>)}</div><Button variant="primary" onClick={() => saveFood({ ...form, nutrients: form })} disabled={!form.name.trim()}>Save food</Button></div>}{selected && <Section title="Add to diary"><div className="lrow"><span className="lrow-m"><span className="lrow-t">{selected.name}</span><span className="lrow-s">{selected.nutrientsPerServing.calories} kcal · {selected.nutrientsPerServing.protein}g protein per serving</span></span></div><SelectRow title="Meal" value={mealType} options={TYPES} onChange={setMealType} /><div className="lrow"><span className="lrow-m"><span className="lrow-t">Servings</span></span><NumberField value={servings} onChange={setServings} /></div><Button variant="primary" onClick={() => logMeal()}>Add to diary</Button></Section>}</>}
    {tab === 'plan' && <><Section title="Today’s meal plan"><p className="muted small">Plan meals alongside your training day. Every planned item shows its nutrition before you log it.</p><Button variant="primary" onClick={makePlan}>Build from saved foods</Button>{plan?.meals?.map(m => <div className="lrow" key={m.mealType}><span className="lrow-m"><span className="lrow-t">{labelOf(m.mealType)} · {m.foodName}</span><span className="lrow-s">{m.servings} serving</span></span><Button size="sm" onClick={() => { setFoodId(m.foodId); setMealType(m.mealType); setTab('add') }}>Add</Button></div>)}{plan && <div className="card" style={{ marginTop: 10 }}><b>Planned totals</b><div className="small muted">{Math.round(plannedTotal.calories)} kcal · {Math.round(plannedTotal.protein)}g protein · {Math.round(plannedTotal.carbs)}g carbs · {Math.round(plannedTotal.fat)}g fat</div></div>}</Section><Section title="Training context"><p className="muted small">Use your workout plan and meal plan together: prepare the food you can actually eat around work, training, and recovery. The next slice adds recipes, shopping lists, leftovers, and shift-aware timing.</p><Button onClick={() => nav('/plan')}>Open workout plan</Button></Section></>}
    {tab === 'targets' && <Section title="Daily nutrition goals"><form onSubmit={saveTargets}>{FIELDS.slice(0, 4).map(([k, label, unit]) => <label className="lrow" key={k}><span className="lrow-m"><span className="lrow-t">{label} ({unit})</span></span><NumberField name={k} defaultValue={targets[k] || ''} /></label>)}<Button variant="primary" type="submit">Save goals</Button></form><p className="muted small">These are personal tracking targets, not medical advice. Adjust them with a qualified professional if needed.</p></Section>}
  </div>
}
